steps:
  - label: ":node: Install dependencies"
    key: "install"
    command: "npm ci"

  - wait

  - label: ":jest: Unit tests"
    command: "npm test -- --watchAll=false"
    env:
      CI: "true"
